"""empty message

Revision ID: f46157487d8c
Revises: 
Create Date: 2022-06-07 10:34:24.358646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46157487d8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image', sa.String(length=30), nullable=False))
    op.drop_column('product', 'thumbnail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('thumbnail', sa.VARCHAR(length=30), nullable=False))
    op.drop_column('product', 'image')
    # ### end Alembic commands ###
